#!/bin/bash

PISOS=3
PLAZAS=5
CAMIONES=5
COCHES=10

mpirun --hostfile hostfile -np 1 parking $PISOS $PLAZAS : -np $CAMIONES camion : -np $COCHES coche
#mpirun --hostfile hostfile -np 1 parking : -np $CAMIONES camion : -np $COCHES coche
